Feature/cli secret
canonical/s3-integrator pull request #76
Opened 2024-11-16 01:24 UTC by sed-i

## Problem
For COS we're now using s3-integrator in all deployments.
With terraform, running actions on a deployment is a bit involved.

## Solution
Add config options for access-key, secret-key.
Since the secrets are already stored in reldata, not much additional harm having them also in the config.
Fixes #62.

2024-11-18 12:46 UTC, phvalguima commented on config.yaml
> +  secret-key:
If we are handling secrets, then we should use [user secrets](https://juju.is/docs/juju/secret#heading--user) here. [One example](https://github.com/canonical/object-storage-integrators/blob/66814cf21e2a8dfcd14a7efcb5f35471e6f6aa87/config.yaml#L20)

2024-11-18 12:58 UTC, phvalguima requested changes
Thanks @sed-i, def. an improvement we need to do. What I would recommend instead is to use Juju's `user-secret` feature. We have another example already doing so. It is also compliant with terraform, [as juju provider allows to create secrets as resources](https://registry.terraform.io/providers/juju/juju/latest/docs/resources/secret).

We have a very similar pattern for `object-storage-integrator`, which is used with azure, [here](https://github.com/canonical/object-storage-integrators/tree/main). I recommend:
- remove the `access-key` and `secret-key` configs and create one config named `credentials`
- pass `credentials` as a type `secret`.

Also, can you update README and the config description to explain how to use `juju add-secret`, as described [here](https://github.com/canonical/object-storage-integrators/blob/66814cf21e2a8dfcd14a7efcb5f35471e6f6aa87/README.md?plain=1#L22-L26).

2024-11-18 18:02 UTC, delgod commented
Hi Leon,

It is an intentional design choice not to have access and secret keys as config values because this approach is not secure.
Please contact Jon if you have any concerns about insecure config options.

On the other hand, we cannot move to user secrets yet because we need to support Juju 2.9 deployments.
Our intent is to eventually add s3 interface support to [object-storage-integrator](https://github.com/canonical/object-storage-integrators) and use it on Juju 3+ deployments.

2024-11-18 18:02 UTC, closed without merging

2024-11-22 05:54 UTC, sed-i commented
Hi @delgod,
Not sure what you mean.
Yes, secrets as config options are not great, but this charm is already leaking same secrets over peer relation.
I.e., afaiu, the secrets are cleartext via `juju show-relation` already.

2025-01-09 04:16 UTC, hloeung commented
Can we reconsider this per @sed-i's comment?